// @ts-nocheck
/* eslint-disable */
// Generated by tauri-specta from src-tauri/src/ipc.rs. Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Static app metadata. Contains nothing about the user or their vaults. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Measures this device and suggests Argon2id parameters (~0.85 s unlock). */
	vaultKdfCalibrate: () => typedError<KdfParams, IpcError_Serialize>(__TAURI_INVOKE("vault_kdf_calibrate")),
	vaultCreate: (request: CreateVaultRequest) => typedError<VaultInfo, IpcError_Serialize>(__TAURI_INVOKE("vault_create", { request })),
	vaultUnlock: (path: string, password: string) => typedError<VaultInfo, IpcError_Serialize>(__TAURI_INVOKE("vault_unlock", { path, password })),
	/**
	 *  Locks, clears our clipboard value and emits `vault://locked`. Returns
	 *  whether a vault was open. Async so a busy clipboard never stalls the UI thread.
	 */
	vaultLock: () => typedError<boolean, IpcError_Serialize>(__TAURI_INVOKE("vault_lock")),
	vaultStatus: () => __TAURI_INVOKE<VaultStatus>("vault_status"),
	vaultIntegrityCheck: () => typedError<IntegrityReport, IpcError_Serialize>(__TAURI_INVOKE("vault_integrity_check")),
	/**
	 *  Same as `vault_create`, but the vault is flagged as a demo (sample data
	 *  arrives in Phase 7+). It's a real encrypted vault with its own password.
	 */
	vaultCreateDemo: (request: CreateVaultRequest) => typedError<VaultInfo, IpcError_Serialize>(__TAURI_INVOKE("vault_create_demo", { request })),
	/**
	 *  Where a new vault named `name` would go, and whether that's a good idea.
	 *  `location` `None` means the default folder.
	 */
	vaultLocationCheck: (location: string | null, name: string) => typedError<LocationCheck, IpcError_Serialize>(__TAURI_INVOKE("vault_location_check", { location, name })),
	/**
	 *  Shows the system folder picker. Returns `None` if cancelled. For
	 *  `ExistingVault`, a folder without a vault header is `vault_not_found`.
	 */
	vaultPickFolder: (purpose: FolderPurpose) => typedError<string | null, IpcError_Serialize>(__TAURI_INVOKE("vault_pick_folder", { purpose })),
	recentVaultsList: () => __TAURI_INVOKE<RecentVault[]>("recent_vaults_list"),
	/**  Removes a vault from the list. The vault's files are not touched. */
	recentVaultsForget: (path: string) => __TAURI_INVOKE<RecentVault[]>("recent_vaults_forget", { path }),
	/**
	 *  Called (debounced) as the user types a new master password. The value is
	 *  scored and dropped; it is never stored or logged.
	 */
	strengthEstimate: (password: string) => __TAURI_INVOKE<StrengthEstimate>("strength_estimate", { password }),
	generatePassword: (options: PasswordOptions) => typedError<Generated, IpcError_Serialize>(__TAURI_INVOKE("generate_password", { options })),
	generatePassphrase: (options: PassphraseOptions) => typedError<Generated, IpcError_Serialize>(__TAURI_INVOKE("generate_passphrase", { options })),
	/**
	 *  Records user activity, pushing the idle-lock deadline back. The UI calls
	 *  it at most every 15 s while the pointer or keyboard is in use. Returns
	 *  false if the vault is locked.
	 */
	sessionTouch: () => __TAURI_INVOKE<boolean>("session_touch"),
	/**  Current lock, clipboard and capture settings. */
	sessionConfigGet: () => __TAURI_INVOKE<SessionConfig>("session_config_get"),
	/**
	 *  Turns screen-capture protection on or off, now and on future launches
	 *  (the lock screen included). Returns the updated settings.
	 */
	captureProtectionSet: (enabled: boolean) => __TAURI_INVOKE<SessionConfig>("capture_protection_set", { enabled }),
	/**
	 *  Why the vault last locked (button or Ctrl+L, idle, Windows lock, sleep),
	 *  so the lock screen can say so. Returns it once, then `None`.
	 */
	sessionTakeLockNotice: () => __TAURI_INVOKE<
/**  The lock button or Ctrl+L. */
{ reason: "manual" } | { reason: "idle"; afterSecs: number } | { reason: "sessionLocked" } | { reason: "signedOut" } | { reason: "disconnected" } | { reason: "sleep" } | { reason: "minimized" } | null>("session_take_lock_notice"),
	/**  Copies non-secret text shown in the UI. Only while unlocked. */
	clipboardCopyPlain: (text: string) => typedError<ClipboardCopy, IpcError_Serialize>(__TAURI_INVOKE("clipboard_copy_plain", { text })),
	/**  "Keep in clipboard": cancels the pending clear. Returns false if none was pending. */
	clipboardCancelClear: () => __TAURI_INVOKE<boolean>("clipboard_cancel_clear"),
	/**  Clears our value from the clipboard now. Returns whether it cleared. */
	clipboardClearNow: () => typedError<boolean, IpcError_Serialize>(__TAURI_INVOKE("clipboard_clear_now")),
};

/** Events */
export const events = {
	clipboardCleared: makeEvent<ClipboardCleared>("clipboard://cleared"),
	vaultLocked: makeEvent<VaultLocked>("vault://locked"),
};

/* Types */
export type AppInfo = {
	name: string,
	version: string,
	buildProfile: BuildProfile,
};

export type BuildProfile = "debug" | "release";

/**
 *  A pending clipboard clear finished (timer, "Clear now", or lock). The UI
 *  dismisses its countdown.
 */
export type ClipboardCleared = null;

export type ClipboardCopy = {
	/**  The clipboard is cleared this many seconds from now. */
	clearAfterSecs: number,
};

export type CloudProvider = "oneDrive" | "dropbox" | "googleDrive" | "iCloud" | "box";

export type CreateVaultRequest = {
	name: string,
	/**  Parent folder. Defaults to `%LOCALAPPDATA%\Vaultair\Vaults`. */
	location: string | null,
	kdf: KdfParams,
	password: string,
};

/**  Stable, machine-readable error codes. The frontend switches on these. */
export type ErrorCode = "vault_locked" | "invalid_input" | "not_found" | "internal" | "wrong_password" | "weak_password" | "vault_not_found" | "vault_exists" | "vault_in_use" | "vault_too_new" | "vault_corrupted" | "clipboard_busy";

export type FolderPurpose = 
/**  Choose where a new vault's folder goes. */
"newVaultLocation" | 
/**  Choose an existing vault's folder (the one containing `vault.vhdr`). */
"existingVault";

/**
 *  A freshly generated value and how strong it is. The value is wiped from
 *  memory when this is dropped (after it's serialized to the UI).
 */
export type Generated = {
	value: string,
	/**  Exact entropy of the generator's output space, in bits. */
	entropyBits: number | null,
	/**  zxcvbn score, 0 (trivial) to 4 (very strong). */
	score: number,
};

export type IntegrityReport = {
	ok: boolean,
};

/**
 *  What a failed command sends to the UI: `vaultair_core::AppError` as a
 *  plain DTO (`{ code, message, field? }`), with no dynamic data.
 */
export type IpcError = IpcError_Serialize | IpcError_Deserialize;

/**
 *  What a failed command sends to the UI: `vaultair_core::AppError` as a
 *  plain DTO (`{ code, message, field? }`), with no dynamic data.
 */
export type IpcError_Deserialize = {
	code: ErrorCode,
	message: string,
	field?: string | null,
};

/**
 *  What a failed command sends to the UI: `vaultair_core::AppError` as a
 *  plain DTO (`{ code, message, field? }`), with no dynamic data.
 */
export type IpcError_Serialize = {
	code: ErrorCode,
	message: string,
	field?: string | null,
};

export type KdfParams = {
	mKib: number,
	t: number,
	p: number,
};

export type LocationCheck = {
	/**  The folder the vault folder will be created in. */
	parentDir: string,
	/**  Where the vault itself will live: `parent_dir\<name>`. */
	vaultDir: string,
	/**  Set when the folder looks synced to a cloud service (warn, don't block). */
	cloudProvider: CloudProvider | null,
	/**  A non-empty folder with this name already exists (create would fail). */
	alreadyExists: boolean,
};

/**
 *  Why the vault last locked, for the lock screen to explain after the
 *  webview reloads. Taken once (`session_take_lock_notice`), so a later
 *  reload doesn't repeat it.
 */
export type LockNotice = 
/**  The lock button or Ctrl+L. */
{ reason: "manual" } | { reason: "idle"; afterSecs: number } | { reason: "sessionLocked" } | { reason: "signedOut" } | { reason: "disconnected" } | { reason: "sleep" } | { reason: "minimized" };

export type PassphraseOptions = {
	/**  3–12 words. */
	words: number,
	/**
	 *  One ASCII punctuation character or a space. Letters and digits would
	 *  blur the word boundaries.
	 */
	separator: string,
	/**  Capitalizes the first letter of every word. */
	capitalize: boolean,
	/**  Appends one random digit to one randomly chosen word. */
	includeNumber: boolean,
};

export type PasswordOptions = {
	/**  8–128 characters. */
	length: number,
	uppercase: boolean,
	lowercase: boolean,
	digits: boolean,
	symbols: boolean,
	/**  Leaves out `Il1O0o`. */
	excludeAmbiguous: boolean,
	/**  Extra characters to leave out. Characters we never use are ignored. */
	exclude: string,
};

/**  A recent vault as the lock screen shows it. */
export type RecentVault = {
	path: string,
	/**
	 *  The folder name. A vault's folder is named after it at creation, so
	 *  this shows the vault's name without storing it or reading the vault.
	 */
	name: string,
	lastOpenedAt: string,
	/**
	 *  False when the folder or its header is gone (moved, deleted, drive
	 *  unplugged). The entry stays until the user removes it.
	 */
	available: boolean,
};

/**
 *  Lock and clipboard behaviour. The defaults are ADR-0004 decision 11.
 *  Phase 15 makes them editable: capture protection in the app config (it
 *  applies while locked), the rest in the vault's settings.
 */
export type SessionConfig = {
	/**  Lock after this many seconds without activity. `None` never locks. */
	idleLockSecs: number | null,
	/**  Lock when Windows locks (Win+L), signs out or disconnects. */
	lockOnSessionLock: boolean,
	lockOnSleep: boolean,
	lockOnMinimize: boolean,
	/**  Copied values are cleared from the clipboard after this long. */
	clipboardClearSecs: number,
	/**  Revealed secrets hide again after this long. */
	revealHideSecs: number,
	/**  Hide the window from screenshots, streaming and screen sharing. */
	captureProtection: boolean,
};

/**
 *  Live feedback for the "create master password" form. Computed in Rust so
 *  the UI and the enforced policy can't disagree.
 */
export type StrengthEstimate = {
	/**  zxcvbn score, 0 (trivial) to 4 (very strong). */
	score: number,
	longEnough: boolean,
	meetsPolicy: boolean,
	/**  zxcvbn's fixed advice strings. They never echo the password. */
	warning: string | null,
	suggestions: string[],
};

/**  Non-secret facts about a vault, safe to show in the UI. */
export type VaultInfo = {
	vaultId: string,
	name: string,
	path: string,
	kdfSummary: string,
	createdAt: string,
	demo: boolean,
};

/**
 *  The vault was locked: by the user, the idle timer, or an OS event (see
 *  `lock::Locker`). The UI reacts by reloading the webview, which discards
 *  every value the JS heap held while unlocked.
 */
export type VaultLocked = null;

export type VaultStatus = { state: "locked" } | { state: "unlocked"; vault: VaultInfo };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

