// @ts-nocheck
/* eslint-disable */
// Generated by tauri-specta from src-tauri/src/ipc.rs. Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Static app metadata. Contains nothing about the user or their vaults. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
export type AppInfo = {
	name: string,
	version: string,
	buildProfile: BuildProfile,
};

export type BuildProfile = "debug" | "release";

/**  Stable, machine-readable error codes. The frontend switches on these. */
export type ErrorCode = "vault_locked" | "invalid_input" | "not_found" | "internal";

