//! Typed IPC surface. `bindings.ts` is generated from this list.

use tauri_specta::{collect_commands, collect_events, Builder};

use crate::{commands, events};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app::app_info,
            commands::vault::vault_kdf_calibrate,
            commands::vault::vault_create,
            commands::vault::vault_unlock,
            commands::vault::vault_lock,
            commands::vault::vault_status,
            commands::vault::vault_integrity_check,
            commands::vault::vault_create_demo,
            commands::vault::vault_location_check,
            commands::vault::vault_pick_folder,
            commands::recent::recent_vaults_list,
            commands::recent::recent_vaults_forget,
            commands::password::strength_estimate,
            commands::generator::generate_password,
            commands::generator::generate_passphrase,
            commands::session::session_touch,
            commands::session::session_config_get,
            commands::session::capture_protection_set,
            commands::session::session_take_lock_notice,
            commands::clipboard::clipboard_copy_plain,
            commands::clipboard::clipboard_cancel_clear,
            commands::clipboard::clipboard_clear_now,
            commands::account::account_list,
            commands::account::account_get,
            commands::account::account_create,
            commands::account::account_update,
            commands::account::account_archive,
            commands::account::account_unarchive,
            commands::account::account_set_favorite,
            commands::account::account_mark_verified,
            commands::account::account_dismiss_notes_suggestions,
            commands::account::account_delete,
            commands::account::account_duplicate_as_template,
            commands::account::account_url_target,
            commands::account::account_open_url,
            commands::account::purpose_list,
            commands::account::tag_list,
            commands::secret::secret_reveal,
            commands::secret::clipboard_copy_secret,
            commands::mfa::mfa_upsert,
            commands::mfa::mfa_delete,
            commands::mfa::mfa_set_backup_codes,
            commands::mfa::mfa_mark_code_used,
            commands::mfa::totp_current_code,
            commands::identity::identity_list,
            commands::identity::identity_refs,
            commands::identity::identity_get,
            commands::identity::identity_overview,
            commands::identity::identity_create,
            commands::identity::identity_update,
            commands::identity::identity_archive,
            commands::identity::identity_unarchive,
            commands::identity::identity_delete,
            commands::identity::identity_assign_accounts,
            commands::identity::contact_point_list,
            commands::identity::dashboard_summary,
            commands::catalog::platform_list,
            commands::catalog::platform_create,
            commands::catalog::platform_update,
            commands::catalog::game_list,
            commands::catalog::game_create,
            commands::catalog::game_update,
            commands::catalog::game_profile_list,
            commands::catalog::game_profile_create,
            commands::catalog::game_profile_update,
            commands::catalog::game_profile_delete,
        ])
        .events(collect_events![
            events::VaultLocked,
            events::ClipboardCleared
        ])
        // Error codes every command can reject with (see `vaultair_core::AppError`).
        .typ::<vaultair_core::ErrorCode>()
}

#[cfg(test)]
pub const BINDINGS_PATH: &str = "../src/ipc/bindings.ts";

#[cfg(test)]
pub fn export_config() -> specta_typescript::Typescript {
    specta_typescript::Typescript::default()
        .header("// @ts-nocheck\n/* eslint-disable */\n// Generated by tauri-specta from src-tauri/src/ipc.rs. Do not edit.")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates the TS bindings. CI runs this test and then fails if the
    /// committed `bindings.ts` changed, so the frontend can't drift from Rust.
    #[test]
    fn export_bindings() {
        builder()
            .export(export_config(), BINDINGS_PATH)
            .expect("failed to export TS bindings");
    }
}
