//! Typed IPC surface. `bindings.ts` is generated from this list.

use tauri_specta::{collect_commands, Builder};

use crate::commands;

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app::app_info,
            commands::vault::vault_kdf_calibrate,
            commands::vault::vault_create,
            commands::vault::vault_unlock,
            commands::vault::vault_lock,
            commands::vault::vault_status,
            commands::vault::vault_integrity_check,
        ])
        // Error codes every command can reject with (see `vaultair_core::AppError`).
        .typ::<vaultair_core::ErrorCode>()
}

#[cfg(test)]
pub const BINDINGS_PATH: &str = "../src/ipc/bindings.ts";

#[cfg(test)]
pub fn export_config() -> specta_typescript::Typescript {
    specta_typescript::Typescript::default()
        .header("// @ts-nocheck\n/* eslint-disable */\n// Generated by tauri-specta from src-tauri/src/ipc.rs. Do not edit.")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates the TS bindings. CI runs this test and then fails if the
    /// committed `bindings.ts` changed, so the frontend can't drift from Rust.
    #[test]
    fn export_bindings() {
        builder()
            .export(export_config(), BINDINGS_PATH)
            .expect("failed to export TS bindings");
    }
}
